import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {
  const [token, setToken] = useState('')
  useEffect(() => {
    setToken(String(localStorage.getItem('token')))
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Trickster (WIP)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Trickster WIP
        </h1>

        <p className={styles.description}>
          {!token && <Link href="/join">Join</Link>}
          {token && <Link href="/my/corpora">Corpora</Link>}
        </p>
      </main>
    </div>
  )
}
